version: '3.8'
services:
  app:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      # Variáveis de ambiente para conectar ao banco de dados
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: db_measurement
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_measurement
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: